Repository pdybowski/happy-app, pull requests merged in 2021-01, with the labels that each got.

#35 Bb 34
  src/shared/view/view.js
  src/utils/api.js
  src/views/news/index.js
Labels: feature

#41 Sport View
  package-lock.json
  src/app.js
  src/environment.js
  src/utils/utils.js
  src/views/news/news.css
  src/views/news/news.js
  src/views/news/newsApi.js
  src/views/news/newsContentProvider.js
  src/views/news/newsList.js
  src/views/news/newsListView.js
  src/views/sport/country.js
  src/views/sport/countryList.js
  src/views/sport/index.js
  src/views/sport/leagueList.js
  src/views/sport/leagues.js
  src/views/sport/sport.css
  src/views/sport/sportApi.js
  src/views/sport/sportContentProvider.js
  src/views/sport/sportView.js
  src/views/sport/team.js
  src/views/sport/teamsList.js
Labels: feature

#39 News view
  src/utils/utils.js
  src/views/news/news.css
  src/views/news/news.js
  src/views/news/newsApi.js
  src/views/news/newsContentProvider.js
  src/views/news/newsList.js
  src/views/news/newsListView.js
Labels: feature

#40 Weather View
  .babelrc
  package-lock.json
  package.json
  src/app.js
  src/environment.js
  src/index.html
  src/views/weather/index.js
  src/views/weather/slider.js
  src/views/weather/svgWeather.js
  src/views/weather/weather.css
  src/views/weather/weatherApi.js
  src/views/weather/weatherContentProvider.js
Labels: feature

#43 Sport view corrected
  package-lock.json
  src/app.js
  src/environment.js
  src/views/sport/country.js
  src/views/sport/countryList.js
  src/views/sport/index.js
  src/views/sport/leagueList.js
  src/views/sport/leagues.js
  src/views/sport/sport.css
  src/views/sport/sportApi.js
  src/views/sport/sportContentProvider.js
  src/views/sport/sportView.js
  src/views/sport/team.js
  src/views/sport/teamsList.js
Labels: feature

#44 News Details Preview
  src/content/styles/global.css
  src/shared/cardPreview/index.js
  src/shared/cardPreview/style.css
  src/shared/closeButton/style.css
  src/shared/navigation/navigator.js
  src/utils/utils.js
  src/views/news/news.css
  src/views/news/news.js
  src/views/news/newsContentProvider.js
  src/views/news/newsList.js
  src/views/news/newsListView.js
Labels: feature

#47 deleted unused views and files, changed html so unused views are not displayed in the app
  src/index.html
  src/views/exampleView/index.js
  src/views/exampleView/modal.js
  src/views/exampleView/style.css
Labels: refactoring

#49 Created readme file and deployed app to gh-pages
  README.md
  package-lock.json
  package.json
  src/content/img/readmeImg.png
Labels: feature

#55 Fix error when using experimental animate function
  src/index.html
  src/shared/cardPreview/index.js
  src/utils/utils.js
Labels: bug

#53 temprature dispalyed in the app is now rounded
  src/views/weather/weatherContentProvider.js
Labels: fix

#62 error popup shows whenever user provides incorrect city name
  src/views/weather/weather.css
  src/views/weather/weatherApi.js
  src/views/weather/weatherContentProvider.js
Labels: feature

#63 implementation statistics
  src/environment.js
  src/shared/button/style.css
  src/views/sport/countries.js
  src/views/sport/league.js
  src/views/sport/leagueList.js
  src/views/sport/leagueView.js
  src/views/sport/leagues.js
  src/views/sport/match.js
  src/views/sport/matchContentProvider.js
  src/views/sport/matchInfo.js
  src/views/sport/matchInfoContentProvider.js
  src/views/sport/matchInfoList.js
  src/views/sport/matchInfoView.js
  src/views/sport/matchView.js
  src/views/sport/matchesList.js
  src/views/sport/season.js
  src/views/sport/seasonContentProvider.js
  src/views/sport/seasonList.js
  src/views/sport/seasonView.js
  src/views/sport/sport.css
  src/views/sport/sportApi.js
  src/views/sport/sportContentProvider.js
  src/views/sport/sportView.js
  src/views/sport/supportedSportCountries.json
  src/views/sport/supportedSportLeague.json
  src/views/sport/team.js
  src/views/sport/teamsList.js
Labels: feature

#65 add error msg when sport data not be fetched
  src/views/sport/matchContentProvider.js
  src/views/sport/matchInfoContentProvider.js
  src/views/sport/matchInfoView.js
  src/views/sport/matchView.js
  src/views/sport/seasonContentProvider.js
  src/views/sport/seasonView.js
  src/views/sport/sport.css
  src/views/sport/sportContentProvider.js
  src/views/sport/sportView.js
Labels: feature
